Algoritmo "Atividade3"



Var
numero1: inteiro
numero2: inteiro

Inicio
escreval ("Digite o primeiro número:")
leia (numero1)
escreval ("Digite o segundo número:")
leia (numero2)

se (numero1 > numero2) entao
escreval ("O número 1 é maior que número 2")

senao

se (numero1 < numero2) entao
escreval ("Número 2 é maior que número 1")

senao
se(numero1 <= numero2) entao
escreval ("Ambos os números são iguais.")

fimSe
fimSe
fimSe

Fimalgoritmo
